const COVID_TYPES = {
  GET_GLOBAL_DATA_STARTED: 'GET_GLOBAL_DATA_STARTED',
  GET_GLOBAL_DATA_SUCCESS: 'GET_GLOBAL_DATA_SUCCESS',
  GET_GLOBAL_DATA_FAILURE: 'GET_GLOBAL_DATA_FAILURE',
};

export default COVID_TYPES;
